### ISSUE TITLE
Proposal: go-prompt and kube-prompt

### ISSUE THREAD

**Issue by c-bata** [uhub/awesome-go#4]
Hi @uhub!
I published go-prompt and kube-prompt last week.
So if you are interested in this library, I want to submit a PR.

* https://github.com/c-bata/go-prompt
* https://github.com/c-bata/kube-prompt

Thanks.

**Comment by ccding** [comment]
sure, I am glad to accept them. My standard is that the projects have enough attentions (e.g., I know it is famous, or it has many starts in gitub)

**Comment by c-bata** [comment]
Now I noticed I forgot closing this.
Thanks.
